version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name : mongodb
    restart: always

  scrapy_spider:
    build:
      context: ./scrapy_project
      dockerfile: Dockerfile_scrapy
    depends_on:
      - mongodb

  dash_app:
    build:
      context: ./dash_app
      dockerfile: Dockerfile_dash
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
      - scrapy_spider

