version: '1.29'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: always
    # mongo doit toujours être en cours d'utilisation pour scrapy

  # première spider scrappant les écoles esf
  scrapy_spider:
    build:
      context: ./scrapy_project 
      dockerfile: Dockerfile_scrapy
    # execute le dockerfile du fichier contenant la spider
    depends_on:
      - mongodb
    # a besoin de mongo pour se lancer

  # seconde spider scrappant le classement esf
  scrapy_spider2:
    build:
      context: ./scrapy_project2
      # execute le dockerfile du fichier contenant la spider
      dockerfile: Dockerfile_scrapy
    depends_on:
      - mongodb
    # a besoin de mongo pour se lancer

  # application dash
  dash_app:
    build:
      context: ./dash_app
      dockerfile: Dockerfile_dash
    # execute le dockerfile du fichier contenant l'application
    ports:
      - "8050:8050"
    # disponible au port 8050
    depends_on:
      scrapy_spider:
        condition: service_completed_successfully
      scrapy_spider2:
        condition: service_completed_successfully
    # a besoin des 2 spiders finies pour se lancer

