FROM python:3.8

WORKDIR /app

COPY requirements.txt .
COPY esf/esf/spiders/esf1.py .

RUN pip install --no-cache-dir -r requirements.txt

# Commande pour démarrer l'araignée Scrapy
CMD ["scrapy", "runspider", "esf1.py"]
