

FROM python:3.8

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Installez les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiez les fichiers nécessaires dans le conteneur
COPY main.py graphs.py france.geojson ./

# Exposez le port sur lequel l'application Dash écoute
EXPOSE 8050

# Commande pour démarrer l'application Dash
CMD ["python", "main.py"]